server:
  port : 7156

spring:
  datasource:
    url : jdbc:mysql://139.224.24.220:3306/passkeeper?serverTimezone=UTC
    username : passkeeper
    password : Wonders,123
    driver-class-name : com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    servlet:
      content-type: text/html
    mode: LEGACYHTML5
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  security:
    user:
      name: actuator
      password: actuator
      roles: ACTUATOR_ADMIN

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.tempest.jdbc.model

management:
  endpoint:
    health:
      show-details: always
      