package com.tempest.jdbc.model;

import java.util.Date;

public class Account {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pk_account.id
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pk_account.userid
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pk_account.account
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	private String account;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pk_account.type
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pk_account.password
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pk_account.property1
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	private String property1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pk_account.property2
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	private String property2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pk_account.property3
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	private String property3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pk_account.property4
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	private String property4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pk_account.property5
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	private String property5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pk_account.property6
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	private String property6;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pk_account.property7
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	private String property7;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pk_account.property8
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	private String property8;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pk_account.property9
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	private String property9;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pk_account.property10
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	private String property10;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pk_account.flag
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	private Integer flag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pk_account.codeversion
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	private Integer codeversion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pk_account.createdate
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	private Date createdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pk_account.updatedate
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	private Date updatedate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pk_account.id
	 * @return  the value of pk_account.id
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pk_account.id
	 * @param id  the value for pk_account.id
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pk_account.userid
	 * @return  the value of pk_account.userid
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pk_account.userid
	 * @param userid  the value for pk_account.userid
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pk_account.account
	 * @return  the value of pk_account.account
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	public String getAccount() {
		return account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pk_account.account
	 * @param account  the value for pk_account.account
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	public void setAccount(String account) {
		this.account = account == null ? null : account.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pk_account.type
	 * @return  the value of pk_account.type
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pk_account.type
	 * @param type  the value for pk_account.type
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	public void setType(String type) {
		this.type = type == null ? null : type.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pk_account.password
	 * @return  the value of pk_account.password
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pk_account.password
	 * @param password  the value for pk_account.password
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pk_account.property1
	 * @return  the value of pk_account.property1
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	public String getProperty1() {
		return property1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pk_account.property1
	 * @param property1  the value for pk_account.property1
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	public void setProperty1(String property1) {
		this.property1 = property1 == null ? null : property1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pk_account.property2
	 * @return  the value of pk_account.property2
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	public String getProperty2() {
		return property2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pk_account.property2
	 * @param property2  the value for pk_account.property2
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	public void setProperty2(String property2) {
		this.property2 = property2 == null ? null : property2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pk_account.property3
	 * @return  the value of pk_account.property3
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	public String getProperty3() {
		return property3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pk_account.property3
	 * @param property3  the value for pk_account.property3
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	public void setProperty3(String property3) {
		this.property3 = property3 == null ? null : property3.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pk_account.property4
	 * @return  the value of pk_account.property4
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	public String getProperty4() {
		return property4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pk_account.property4
	 * @param property4  the value for pk_account.property4
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	public void setProperty4(String property4) {
		this.property4 = property4 == null ? null : property4.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pk_account.property5
	 * @return  the value of pk_account.property5
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	public String getProperty5() {
		return property5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pk_account.property5
	 * @param property5  the value for pk_account.property5
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	public void setProperty5(String property5) {
		this.property5 = property5 == null ? null : property5.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pk_account.property6
	 * @return  the value of pk_account.property6
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	public String getProperty6() {
		return property6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pk_account.property6
	 * @param property6  the value for pk_account.property6
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	public void setProperty6(String property6) {
		this.property6 = property6 == null ? null : property6.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pk_account.property7
	 * @return  the value of pk_account.property7
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	public String getProperty7() {
		return property7;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pk_account.property7
	 * @param property7  the value for pk_account.property7
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	public void setProperty7(String property7) {
		this.property7 = property7 == null ? null : property7.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pk_account.property8
	 * @return  the value of pk_account.property8
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	public String getProperty8() {
		return property8;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pk_account.property8
	 * @param property8  the value for pk_account.property8
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	public void setProperty8(String property8) {
		this.property8 = property8 == null ? null : property8.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pk_account.property9
	 * @return  the value of pk_account.property9
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	public String getProperty9() {
		return property9;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pk_account.property9
	 * @param property9  the value for pk_account.property9
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	public void setProperty9(String property9) {
		this.property9 = property9 == null ? null : property9.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pk_account.property10
	 * @return  the value of pk_account.property10
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	public String getProperty10() {
		return property10;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pk_account.property10
	 * @param property10  the value for pk_account.property10
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	public void setProperty10(String property10) {
		this.property10 = property10 == null ? null : property10.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pk_account.flag
	 * @return  the value of pk_account.flag
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	public Integer getFlag() {
		return flag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pk_account.flag
	 * @param flag  the value for pk_account.flag
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	public void setFlag(Integer flag) {
		this.flag = flag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pk_account.codeversion
	 * @return  the value of pk_account.codeversion
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	public Integer getCodeversion() {
		return codeversion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pk_account.codeversion
	 * @param codeversion  the value for pk_account.codeversion
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	public void setCodeversion(Integer codeversion) {
		this.codeversion = codeversion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pk_account.createdate
	 * @return  the value of pk_account.createdate
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	public Date getCreatedate() {
		return createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pk_account.createdate
	 * @param createdate  the value for pk_account.createdate
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pk_account.updatedate
	 * @return  the value of pk_account.updatedate
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	public Date getUpdatedate() {
		return updatedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pk_account.updatedate
	 * @param updatedate  the value for pk_account.updatedate
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	public void setUpdatedate(Date updatedate) {
		this.updatedate = updatedate;
	}
}