package com.tempest.jdbc.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SubjectExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pk_subject
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pk_subject
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pk_subject
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pk_subject
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	public SubjectExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pk_subject
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pk_subject
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pk_subject
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pk_subject
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pk_subject
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pk_subject
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pk_subject
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pk_subject
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pk_subject
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pk_subject
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table pk_subject
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andUseridIsNull() {
			addCriterion("userid is null");
			return (Criteria) this;
		}

		public Criteria andUseridIsNotNull() {
			addCriterion("userid is not null");
			return (Criteria) this;
		}

		public Criteria andUseridEqualTo(String value) {
			addCriterion("userid =", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotEqualTo(String value) {
			addCriterion("userid <>", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThan(String value) {
			addCriterion("userid >", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThanOrEqualTo(String value) {
			addCriterion("userid >=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThan(String value) {
			addCriterion("userid <", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThanOrEqualTo(String value) {
			addCriterion("userid <=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLike(String value) {
			addCriterion("userid like", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotLike(String value) {
			addCriterion("userid not like", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridIn(List<String> values) {
			addCriterion("userid in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotIn(List<String> values) {
			addCriterion("userid not in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridBetween(String value1, String value2) {
			addCriterion("userid between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotBetween(String value1, String value2) {
			addCriterion("userid not between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andObjtypeIsNull() {
			addCriterion("objtype is null");
			return (Criteria) this;
		}

		public Criteria andObjtypeIsNotNull() {
			addCriterion("objtype is not null");
			return (Criteria) this;
		}

		public Criteria andObjtypeEqualTo(String value) {
			addCriterion("objtype =", value, "objtype");
			return (Criteria) this;
		}

		public Criteria andObjtypeNotEqualTo(String value) {
			addCriterion("objtype <>", value, "objtype");
			return (Criteria) this;
		}

		public Criteria andObjtypeGreaterThan(String value) {
			addCriterion("objtype >", value, "objtype");
			return (Criteria) this;
		}

		public Criteria andObjtypeGreaterThanOrEqualTo(String value) {
			addCriterion("objtype >=", value, "objtype");
			return (Criteria) this;
		}

		public Criteria andObjtypeLessThan(String value) {
			addCriterion("objtype <", value, "objtype");
			return (Criteria) this;
		}

		public Criteria andObjtypeLessThanOrEqualTo(String value) {
			addCriterion("objtype <=", value, "objtype");
			return (Criteria) this;
		}

		public Criteria andObjtypeLike(String value) {
			addCriterion("objtype like", value, "objtype");
			return (Criteria) this;
		}

		public Criteria andObjtypeNotLike(String value) {
			addCriterion("objtype not like", value, "objtype");
			return (Criteria) this;
		}

		public Criteria andObjtypeIn(List<String> values) {
			addCriterion("objtype in", values, "objtype");
			return (Criteria) this;
		}

		public Criteria andObjtypeNotIn(List<String> values) {
			addCriterion("objtype not in", values, "objtype");
			return (Criteria) this;
		}

		public Criteria andObjtypeBetween(String value1, String value2) {
			addCriterion("objtype between", value1, value2, "objtype");
			return (Criteria) this;
		}

		public Criteria andObjtypeNotBetween(String value1, String value2) {
			addCriterion("objtype not between", value1, value2, "objtype");
			return (Criteria) this;
		}

		public Criteria andObjidIsNull() {
			addCriterion("objid is null");
			return (Criteria) this;
		}

		public Criteria andObjidIsNotNull() {
			addCriterion("objid is not null");
			return (Criteria) this;
		}

		public Criteria andObjidEqualTo(String value) {
			addCriterion("objid =", value, "objid");
			return (Criteria) this;
		}

		public Criteria andObjidNotEqualTo(String value) {
			addCriterion("objid <>", value, "objid");
			return (Criteria) this;
		}

		public Criteria andObjidGreaterThan(String value) {
			addCriterion("objid >", value, "objid");
			return (Criteria) this;
		}

		public Criteria andObjidGreaterThanOrEqualTo(String value) {
			addCriterion("objid >=", value, "objid");
			return (Criteria) this;
		}

		public Criteria andObjidLessThan(String value) {
			addCriterion("objid <", value, "objid");
			return (Criteria) this;
		}

		public Criteria andObjidLessThanOrEqualTo(String value) {
			addCriterion("objid <=", value, "objid");
			return (Criteria) this;
		}

		public Criteria andObjidLike(String value) {
			addCriterion("objid like", value, "objid");
			return (Criteria) this;
		}

		public Criteria andObjidNotLike(String value) {
			addCriterion("objid not like", value, "objid");
			return (Criteria) this;
		}

		public Criteria andObjidIn(List<String> values) {
			addCriterion("objid in", values, "objid");
			return (Criteria) this;
		}

		public Criteria andObjidNotIn(List<String> values) {
			addCriterion("objid not in", values, "objid");
			return (Criteria) this;
		}

		public Criteria andObjidBetween(String value1, String value2) {
			addCriterion("objid between", value1, value2, "objid");
			return (Criteria) this;
		}

		public Criteria andObjidNotBetween(String value1, String value2) {
			addCriterion("objid not between", value1, value2, "objid");
			return (Criteria) this;
		}

		public Criteria andObjpassIsNull() {
			addCriterion("objpass is null");
			return (Criteria) this;
		}

		public Criteria andObjpassIsNotNull() {
			addCriterion("objpass is not null");
			return (Criteria) this;
		}

		public Criteria andObjpassEqualTo(String value) {
			addCriterion("objpass =", value, "objpass");
			return (Criteria) this;
		}

		public Criteria andObjpassNotEqualTo(String value) {
			addCriterion("objpass <>", value, "objpass");
			return (Criteria) this;
		}

		public Criteria andObjpassGreaterThan(String value) {
			addCriterion("objpass >", value, "objpass");
			return (Criteria) this;
		}

		public Criteria andObjpassGreaterThanOrEqualTo(String value) {
			addCriterion("objpass >=", value, "objpass");
			return (Criteria) this;
		}

		public Criteria andObjpassLessThan(String value) {
			addCriterion("objpass <", value, "objpass");
			return (Criteria) this;
		}

		public Criteria andObjpassLessThanOrEqualTo(String value) {
			addCriterion("objpass <=", value, "objpass");
			return (Criteria) this;
		}

		public Criteria andObjpassLike(String value) {
			addCriterion("objpass like", value, "objpass");
			return (Criteria) this;
		}

		public Criteria andObjpassNotLike(String value) {
			addCriterion("objpass not like", value, "objpass");
			return (Criteria) this;
		}

		public Criteria andObjpassIn(List<String> values) {
			addCriterion("objpass in", values, "objpass");
			return (Criteria) this;
		}

		public Criteria andObjpassNotIn(List<String> values) {
			addCriterion("objpass not in", values, "objpass");
			return (Criteria) this;
		}

		public Criteria andObjpassBetween(String value1, String value2) {
			addCriterion("objpass between", value1, value2, "objpass");
			return (Criteria) this;
		}

		public Criteria andObjpassNotBetween(String value1, String value2) {
			addCriterion("objpass not between", value1, value2, "objpass");
			return (Criteria) this;
		}

		public Criteria andObjquerypassIsNull() {
			addCriterion("objquerypass is null");
			return (Criteria) this;
		}

		public Criteria andObjquerypassIsNotNull() {
			addCriterion("objquerypass is not null");
			return (Criteria) this;
		}

		public Criteria andObjquerypassEqualTo(String value) {
			addCriterion("objquerypass =", value, "objquerypass");
			return (Criteria) this;
		}

		public Criteria andObjquerypassNotEqualTo(String value) {
			addCriterion("objquerypass <>", value, "objquerypass");
			return (Criteria) this;
		}

		public Criteria andObjquerypassGreaterThan(String value) {
			addCriterion("objquerypass >", value, "objquerypass");
			return (Criteria) this;
		}

		public Criteria andObjquerypassGreaterThanOrEqualTo(String value) {
			addCriterion("objquerypass >=", value, "objquerypass");
			return (Criteria) this;
		}

		public Criteria andObjquerypassLessThan(String value) {
			addCriterion("objquerypass <", value, "objquerypass");
			return (Criteria) this;
		}

		public Criteria andObjquerypassLessThanOrEqualTo(String value) {
			addCriterion("objquerypass <=", value, "objquerypass");
			return (Criteria) this;
		}

		public Criteria andObjquerypassLike(String value) {
			addCriterion("objquerypass like", value, "objquerypass");
			return (Criteria) this;
		}

		public Criteria andObjquerypassNotLike(String value) {
			addCriterion("objquerypass not like", value, "objquerypass");
			return (Criteria) this;
		}

		public Criteria andObjquerypassIn(List<String> values) {
			addCriterion("objquerypass in", values, "objquerypass");
			return (Criteria) this;
		}

		public Criteria andObjquerypassNotIn(List<String> values) {
			addCriterion("objquerypass not in", values, "objquerypass");
			return (Criteria) this;
		}

		public Criteria andObjquerypassBetween(String value1, String value2) {
			addCriterion("objquerypass between", value1, value2, "objquerypass");
			return (Criteria) this;
		}

		public Criteria andObjquerypassNotBetween(String value1, String value2) {
			addCriterion("objquerypass not between", value1, value2, "objquerypass");
			return (Criteria) this;
		}

		public Criteria andPhoneIsNull() {
			addCriterion("phone is null");
			return (Criteria) this;
		}

		public Criteria andPhoneIsNotNull() {
			addCriterion("phone is not null");
			return (Criteria) this;
		}

		public Criteria andPhoneEqualTo(String value) {
			addCriterion("phone =", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotEqualTo(String value) {
			addCriterion("phone <>", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneGreaterThan(String value) {
			addCriterion("phone >", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneGreaterThanOrEqualTo(String value) {
			addCriterion("phone >=", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLessThan(String value) {
			addCriterion("phone <", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLessThanOrEqualTo(String value) {
			addCriterion("phone <=", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLike(String value) {
			addCriterion("phone like", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotLike(String value) {
			addCriterion("phone not like", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneIn(List<String> values) {
			addCriterion("phone in", values, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotIn(List<String> values) {
			addCriterion("phone not in", values, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneBetween(String value1, String value2) {
			addCriterion("phone between", value1, value2, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotBetween(String value1, String value2) {
			addCriterion("phone not between", value1, value2, "phone");
			return (Criteria) this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("email is null");
			return (Criteria) this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("email is not null");
			return (Criteria) this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("email =", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("email <>", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("email >", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("email >=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("email <", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("email <=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("email like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("email not like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("email in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("email not in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("email between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("email not between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andTipquestionIsNull() {
			addCriterion("tipquestion is null");
			return (Criteria) this;
		}

		public Criteria andTipquestionIsNotNull() {
			addCriterion("tipquestion is not null");
			return (Criteria) this;
		}

		public Criteria andTipquestionEqualTo(String value) {
			addCriterion("tipquestion =", value, "tipquestion");
			return (Criteria) this;
		}

		public Criteria andTipquestionNotEqualTo(String value) {
			addCriterion("tipquestion <>", value, "tipquestion");
			return (Criteria) this;
		}

		public Criteria andTipquestionGreaterThan(String value) {
			addCriterion("tipquestion >", value, "tipquestion");
			return (Criteria) this;
		}

		public Criteria andTipquestionGreaterThanOrEqualTo(String value) {
			addCriterion("tipquestion >=", value, "tipquestion");
			return (Criteria) this;
		}

		public Criteria andTipquestionLessThan(String value) {
			addCriterion("tipquestion <", value, "tipquestion");
			return (Criteria) this;
		}

		public Criteria andTipquestionLessThanOrEqualTo(String value) {
			addCriterion("tipquestion <=", value, "tipquestion");
			return (Criteria) this;
		}

		public Criteria andTipquestionLike(String value) {
			addCriterion("tipquestion like", value, "tipquestion");
			return (Criteria) this;
		}

		public Criteria andTipquestionNotLike(String value) {
			addCriterion("tipquestion not like", value, "tipquestion");
			return (Criteria) this;
		}

		public Criteria andTipquestionIn(List<String> values) {
			addCriterion("tipquestion in", values, "tipquestion");
			return (Criteria) this;
		}

		public Criteria andTipquestionNotIn(List<String> values) {
			addCriterion("tipquestion not in", values, "tipquestion");
			return (Criteria) this;
		}

		public Criteria andTipquestionBetween(String value1, String value2) {
			addCriterion("tipquestion between", value1, value2, "tipquestion");
			return (Criteria) this;
		}

		public Criteria andTipquestionNotBetween(String value1, String value2) {
			addCriterion("tipquestion not between", value1, value2, "tipquestion");
			return (Criteria) this;
		}

		public Criteria andTipanswerIsNull() {
			addCriterion("tipanswer is null");
			return (Criteria) this;
		}

		public Criteria andTipanswerIsNotNull() {
			addCriterion("tipanswer is not null");
			return (Criteria) this;
		}

		public Criteria andTipanswerEqualTo(String value) {
			addCriterion("tipanswer =", value, "tipanswer");
			return (Criteria) this;
		}

		public Criteria andTipanswerNotEqualTo(String value) {
			addCriterion("tipanswer <>", value, "tipanswer");
			return (Criteria) this;
		}

		public Criteria andTipanswerGreaterThan(String value) {
			addCriterion("tipanswer >", value, "tipanswer");
			return (Criteria) this;
		}

		public Criteria andTipanswerGreaterThanOrEqualTo(String value) {
			addCriterion("tipanswer >=", value, "tipanswer");
			return (Criteria) this;
		}

		public Criteria andTipanswerLessThan(String value) {
			addCriterion("tipanswer <", value, "tipanswer");
			return (Criteria) this;
		}

		public Criteria andTipanswerLessThanOrEqualTo(String value) {
			addCriterion("tipanswer <=", value, "tipanswer");
			return (Criteria) this;
		}

		public Criteria andTipanswerLike(String value) {
			addCriterion("tipanswer like", value, "tipanswer");
			return (Criteria) this;
		}

		public Criteria andTipanswerNotLike(String value) {
			addCriterion("tipanswer not like", value, "tipanswer");
			return (Criteria) this;
		}

		public Criteria andTipanswerIn(List<String> values) {
			addCriterion("tipanswer in", values, "tipanswer");
			return (Criteria) this;
		}

		public Criteria andTipanswerNotIn(List<String> values) {
			addCriterion("tipanswer not in", values, "tipanswer");
			return (Criteria) this;
		}

		public Criteria andTipanswerBetween(String value1, String value2) {
			addCriterion("tipanswer between", value1, value2, "tipanswer");
			return (Criteria) this;
		}

		public Criteria andTipanswerNotBetween(String value1, String value2) {
			addCriterion("tipanswer not between", value1, value2, "tipanswer");
			return (Criteria) this;
		}

		public Criteria andWeburlIsNull() {
			addCriterion("weburl is null");
			return (Criteria) this;
		}

		public Criteria andWeburlIsNotNull() {
			addCriterion("weburl is not null");
			return (Criteria) this;
		}

		public Criteria andWeburlEqualTo(String value) {
			addCriterion("weburl =", value, "weburl");
			return (Criteria) this;
		}

		public Criteria andWeburlNotEqualTo(String value) {
			addCriterion("weburl <>", value, "weburl");
			return (Criteria) this;
		}

		public Criteria andWeburlGreaterThan(String value) {
			addCriterion("weburl >", value, "weburl");
			return (Criteria) this;
		}

		public Criteria andWeburlGreaterThanOrEqualTo(String value) {
			addCriterion("weburl >=", value, "weburl");
			return (Criteria) this;
		}

		public Criteria andWeburlLessThan(String value) {
			addCriterion("weburl <", value, "weburl");
			return (Criteria) this;
		}

		public Criteria andWeburlLessThanOrEqualTo(String value) {
			addCriterion("weburl <=", value, "weburl");
			return (Criteria) this;
		}

		public Criteria andWeburlLike(String value) {
			addCriterion("weburl like", value, "weburl");
			return (Criteria) this;
		}

		public Criteria andWeburlNotLike(String value) {
			addCriterion("weburl not like", value, "weburl");
			return (Criteria) this;
		}

		public Criteria andWeburlIn(List<String> values) {
			addCriterion("weburl in", values, "weburl");
			return (Criteria) this;
		}

		public Criteria andWeburlNotIn(List<String> values) {
			addCriterion("weburl not in", values, "weburl");
			return (Criteria) this;
		}

		public Criteria andWeburlBetween(String value1, String value2) {
			addCriterion("weburl between", value1, value2, "weburl");
			return (Criteria) this;
		}

		public Criteria andWeburlNotBetween(String value1, String value2) {
			addCriterion("weburl not between", value1, value2, "weburl");
			return (Criteria) this;
		}

		public Criteria andBusinameIsNull() {
			addCriterion("businame is null");
			return (Criteria) this;
		}

		public Criteria andBusinameIsNotNull() {
			addCriterion("businame is not null");
			return (Criteria) this;
		}

		public Criteria andBusinameEqualTo(String value) {
			addCriterion("businame =", value, "businame");
			return (Criteria) this;
		}

		public Criteria andBusinameNotEqualTo(String value) {
			addCriterion("businame <>", value, "businame");
			return (Criteria) this;
		}

		public Criteria andBusinameGreaterThan(String value) {
			addCriterion("businame >", value, "businame");
			return (Criteria) this;
		}

		public Criteria andBusinameGreaterThanOrEqualTo(String value) {
			addCriterion("businame >=", value, "businame");
			return (Criteria) this;
		}

		public Criteria andBusinameLessThan(String value) {
			addCriterion("businame <", value, "businame");
			return (Criteria) this;
		}

		public Criteria andBusinameLessThanOrEqualTo(String value) {
			addCriterion("businame <=", value, "businame");
			return (Criteria) this;
		}

		public Criteria andBusinameLike(String value) {
			addCriterion("businame like", value, "businame");
			return (Criteria) this;
		}

		public Criteria andBusinameNotLike(String value) {
			addCriterion("businame not like", value, "businame");
			return (Criteria) this;
		}

		public Criteria andBusinameIn(List<String> values) {
			addCriterion("businame in", values, "businame");
			return (Criteria) this;
		}

		public Criteria andBusinameNotIn(List<String> values) {
			addCriterion("businame not in", values, "businame");
			return (Criteria) this;
		}

		public Criteria andBusinameBetween(String value1, String value2) {
			addCriterion("businame between", value1, value2, "businame");
			return (Criteria) this;
		}

		public Criteria andBusinameNotBetween(String value1, String value2) {
			addCriterion("businame not between", value1, value2, "businame");
			return (Criteria) this;
		}

		public Criteria andLimitsIsNull() {
			addCriterion("limits is null");
			return (Criteria) this;
		}

		public Criteria andLimitsIsNotNull() {
			addCriterion("limits is not null");
			return (Criteria) this;
		}

		public Criteria andLimitsEqualTo(String value) {
			addCriterion("limits =", value, "limits");
			return (Criteria) this;
		}

		public Criteria andLimitsNotEqualTo(String value) {
			addCriterion("limits <>", value, "limits");
			return (Criteria) this;
		}

		public Criteria andLimitsGreaterThan(String value) {
			addCriterion("limits >", value, "limits");
			return (Criteria) this;
		}

		public Criteria andLimitsGreaterThanOrEqualTo(String value) {
			addCriterion("limits >=", value, "limits");
			return (Criteria) this;
		}

		public Criteria andLimitsLessThan(String value) {
			addCriterion("limits <", value, "limits");
			return (Criteria) this;
		}

		public Criteria andLimitsLessThanOrEqualTo(String value) {
			addCriterion("limits <=", value, "limits");
			return (Criteria) this;
		}

		public Criteria andLimitsLike(String value) {
			addCriterion("limits like", value, "limits");
			return (Criteria) this;
		}

		public Criteria andLimitsNotLike(String value) {
			addCriterion("limits not like", value, "limits");
			return (Criteria) this;
		}

		public Criteria andLimitsIn(List<String> values) {
			addCriterion("limits in", values, "limits");
			return (Criteria) this;
		}

		public Criteria andLimitsNotIn(List<String> values) {
			addCriterion("limits not in", values, "limits");
			return (Criteria) this;
		}

		public Criteria andLimitsBetween(String value1, String value2) {
			addCriterion("limits between", value1, value2, "limits");
			return (Criteria) this;
		}

		public Criteria andLimitsNotBetween(String value1, String value2) {
			addCriterion("limits not between", value1, value2, "limits");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("remark is null");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("remark is not null");
			return (Criteria) this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("remark =", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("remark <>", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("remark >", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("remark >=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("remark <", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("remark <=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("remark like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("remark not like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkIn(List<String> values) {
			addCriterion("remark in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotIn(List<String> values) {
			addCriterion("remark not in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("remark between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("remark not between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andAddtimeIsNull() {
			addCriterion("addtime is null");
			return (Criteria) this;
		}

		public Criteria andAddtimeIsNotNull() {
			addCriterion("addtime is not null");
			return (Criteria) this;
		}

		public Criteria andAddtimeEqualTo(Date value) {
			addCriterion("addtime =", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeNotEqualTo(Date value) {
			addCriterion("addtime <>", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeGreaterThan(Date value) {
			addCriterion("addtime >", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeGreaterThanOrEqualTo(Date value) {
			addCriterion("addtime >=", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeLessThan(Date value) {
			addCriterion("addtime <", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeLessThanOrEqualTo(Date value) {
			addCriterion("addtime <=", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeIn(List<Date> values) {
			addCriterion("addtime in", values, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeNotIn(List<Date> values) {
			addCriterion("addtime not in", values, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeBetween(Date value1, Date value2) {
			addCriterion("addtime between", value1, value2, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeNotBetween(Date value1, Date value2) {
			addCriterion("addtime not between", value1, value2, "addtime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeIsNull() {
			addCriterion("updatetime is null");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeIsNotNull() {
			addCriterion("updatetime is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeEqualTo(Date value) {
			addCriterion("updatetime =", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeNotEqualTo(Date value) {
			addCriterion("updatetime <>", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeGreaterThan(Date value) {
			addCriterion("updatetime >", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("updatetime >=", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeLessThan(Date value) {
			addCriterion("updatetime <", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
			addCriterion("updatetime <=", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeIn(List<Date> values) {
			addCriterion("updatetime in", values, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeNotIn(List<Date> values) {
			addCriterion("updatetime not in", values, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeBetween(Date value1, Date value2) {
			addCriterion("updatetime between", value1, value2, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
			addCriterion("updatetime not between", value1, value2, "updatetime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table pk_subject
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pk_subject
     *
     * @mbg.generated do_not_delete_during_merge Fri Jun 19 13:48:00 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}