package com.tempest.jdbc.model;

import java.util.Date;

public class Subject {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pk_subject.id
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pk_subject.userid
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	private String userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pk_subject.objtype
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	private String objtype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pk_subject.objid
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	private String objid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pk_subject.objpass
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	private String objpass;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pk_subject.objquerypass
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	private String objquerypass;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pk_subject.phone
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pk_subject.email
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pk_subject.tipquestion
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	private String tipquestion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pk_subject.tipanswer
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	private String tipanswer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pk_subject.weburl
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	private String weburl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pk_subject.businame
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	private String businame;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pk_subject.limits
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	private String limits;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pk_subject.remark
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pk_subject.addtime
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	private Date addtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pk_subject.updatetime
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	private Date updatetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pk_subject.id
	 * @return  the value of pk_subject.id
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pk_subject.id
	 * @param id  the value for pk_subject.id
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pk_subject.userid
	 * @return  the value of pk_subject.userid
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	public String getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pk_subject.userid
	 * @param userid  the value for pk_subject.userid
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	public void setUserid(String userid) {
		this.userid = userid == null ? null : userid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pk_subject.objtype
	 * @return  the value of pk_subject.objtype
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	public String getObjtype() {
		return objtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pk_subject.objtype
	 * @param objtype  the value for pk_subject.objtype
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	public void setObjtype(String objtype) {
		this.objtype = objtype == null ? null : objtype.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pk_subject.objid
	 * @return  the value of pk_subject.objid
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	public String getObjid() {
		return objid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pk_subject.objid
	 * @param objid  the value for pk_subject.objid
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	public void setObjid(String objid) {
		this.objid = objid == null ? null : objid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pk_subject.objpass
	 * @return  the value of pk_subject.objpass
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	public String getObjpass() {
		return objpass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pk_subject.objpass
	 * @param objpass  the value for pk_subject.objpass
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	public void setObjpass(String objpass) {
		this.objpass = objpass == null ? null : objpass.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pk_subject.objquerypass
	 * @return  the value of pk_subject.objquerypass
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	public String getObjquerypass() {
		return objquerypass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pk_subject.objquerypass
	 * @param objquerypass  the value for pk_subject.objquerypass
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	public void setObjquerypass(String objquerypass) {
		this.objquerypass = objquerypass == null ? null : objquerypass.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pk_subject.phone
	 * @return  the value of pk_subject.phone
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pk_subject.phone
	 * @param phone  the value for pk_subject.phone
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pk_subject.email
	 * @return  the value of pk_subject.email
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pk_subject.email
	 * @param email  the value for pk_subject.email
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pk_subject.tipquestion
	 * @return  the value of pk_subject.tipquestion
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	public String getTipquestion() {
		return tipquestion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pk_subject.tipquestion
	 * @param tipquestion  the value for pk_subject.tipquestion
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	public void setTipquestion(String tipquestion) {
		this.tipquestion = tipquestion == null ? null : tipquestion.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pk_subject.tipanswer
	 * @return  the value of pk_subject.tipanswer
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	public String getTipanswer() {
		return tipanswer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pk_subject.tipanswer
	 * @param tipanswer  the value for pk_subject.tipanswer
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	public void setTipanswer(String tipanswer) {
		this.tipanswer = tipanswer == null ? null : tipanswer.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pk_subject.weburl
	 * @return  the value of pk_subject.weburl
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	public String getWeburl() {
		return weburl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pk_subject.weburl
	 * @param weburl  the value for pk_subject.weburl
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	public void setWeburl(String weburl) {
		this.weburl = weburl == null ? null : weburl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pk_subject.businame
	 * @return  the value of pk_subject.businame
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	public String getBusiname() {
		return businame;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pk_subject.businame
	 * @param businame  the value for pk_subject.businame
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	public void setBusiname(String businame) {
		this.businame = businame == null ? null : businame.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pk_subject.limits
	 * @return  the value of pk_subject.limits
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	public String getLimits() {
		return limits;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pk_subject.limits
	 * @param limits  the value for pk_subject.limits
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	public void setLimits(String limits) {
		this.limits = limits == null ? null : limits.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pk_subject.remark
	 * @return  the value of pk_subject.remark
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pk_subject.remark
	 * @param remark  the value for pk_subject.remark
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pk_subject.addtime
	 * @return  the value of pk_subject.addtime
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	public Date getAddtime() {
		return addtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pk_subject.addtime
	 * @param addtime  the value for pk_subject.addtime
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	public void setAddtime(Date addtime) {
		this.addtime = addtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pk_subject.updatetime
	 * @return  the value of pk_subject.updatetime
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	public Date getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pk_subject.updatetime
	 * @param updatetime  the value for pk_subject.updatetime
	 * @mbg.generated  Mon Jun 22 14:12:10 CST 2020
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}
}