package com.tempest.jdbc.model;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pk_user.id
     *
     * @mbg.generated Wed Jul 15 14:52:38 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pk_user.username
     *
     * @mbg.generated Wed Jul 15 14:52:38 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pk_user.password
     *
     * @mbg.generated Wed Jul 15 14:52:38 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pk_user.realname
     *
     * @mbg.generated Wed Jul 15 14:52:38 CST 2020
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pk_user.email
     *
     * @mbg.generated Wed Jul 15 14:52:38 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pk_user.flag
     *
     * @mbg.generated Wed Jul 15 14:52:38 CST 2020
     */
    private Integer flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pk_user.registerdate
     *
     * @mbg.generated Wed Jul 15 14:52:38 CST 2020
     */
    private Date registerdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pk_user.logindate
     *
     * @mbg.generated Wed Jul 15 14:52:38 CST 2020
     */
    private Date logindate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pk_user.id
     *
     * @return the value of pk_user.id
     *
     * @mbg.generated Wed Jul 15 14:52:38 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pk_user.id
     *
     * @param id the value for pk_user.id
     *
     * @mbg.generated Wed Jul 15 14:52:38 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pk_user.username
     *
     * @return the value of pk_user.username
     *
     * @mbg.generated Wed Jul 15 14:52:38 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pk_user.username
     *
     * @param username the value for pk_user.username
     *
     * @mbg.generated Wed Jul 15 14:52:38 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pk_user.password
     *
     * @return the value of pk_user.password
     *
     * @mbg.generated Wed Jul 15 14:52:38 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pk_user.password
     *
     * @param password the value for pk_user.password
     *
     * @mbg.generated Wed Jul 15 14:52:38 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pk_user.realname
     *
     * @return the value of pk_user.realname
     *
     * @mbg.generated Wed Jul 15 14:52:38 CST 2020
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pk_user.realname
     *
     * @param realname the value for pk_user.realname
     *
     * @mbg.generated Wed Jul 15 14:52:38 CST 2020
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pk_user.email
     *
     * @return the value of pk_user.email
     *
     * @mbg.generated Wed Jul 15 14:52:38 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pk_user.email
     *
     * @param email the value for pk_user.email
     *
     * @mbg.generated Wed Jul 15 14:52:38 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pk_user.flag
     *
     * @return the value of pk_user.flag
     *
     * @mbg.generated Wed Jul 15 14:52:38 CST 2020
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pk_user.flag
     *
     * @param flag the value for pk_user.flag
     *
     * @mbg.generated Wed Jul 15 14:52:38 CST 2020
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pk_user.registerdate
     *
     * @return the value of pk_user.registerdate
     *
     * @mbg.generated Wed Jul 15 14:52:38 CST 2020
     */
    public Date getRegisterdate() {
        return registerdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pk_user.registerdate
     *
     * @param registerdate the value for pk_user.registerdate
     *
     * @mbg.generated Wed Jul 15 14:52:38 CST 2020
     */
    public void setRegisterdate(Date registerdate) {
        this.registerdate = registerdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pk_user.logindate
     *
     * @return the value of pk_user.logindate
     *
     * @mbg.generated Wed Jul 15 14:52:38 CST 2020
     */
    public Date getLogindate() {
        return logindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pk_user.logindate
     *
     * @param logindate the value for pk_user.logindate
     *
     * @mbg.generated Wed Jul 15 14:52:38 CST 2020
     */
    public void setLogindate(Date logindate) {
        this.logindate = logindate;
    }
}