package com.tempest.jdbc.dao;

import com.tempest.jdbc.model.Account;
import com.tempest.jdbc.model.AccountExample;
import java.util.List;

public interface AccountMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pk_account
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pk_account
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	int insert(Account record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pk_account
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	int insertSelective(Account record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pk_account
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	List<Account> selectByExample(AccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pk_account
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	Account selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pk_account
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	int updateByPrimaryKeySelective(Account record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pk_account
	 * @mbg.generated  Thu Jun 18 18:36:51 CST 2020
	 */
	int updateByPrimaryKey(Account record);
}