package com.tempest.jdbc.dao;

import com.tempest.jdbc.model.User;
import com.tempest.jdbc.model.UserExample;
import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pk_user
     *
     * @mbg.generated Wed Jul 15 14:52:38 CST 2020
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pk_user
     *
     * @mbg.generated Wed Jul 15 14:52:38 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pk_user
     *
     * @mbg.generated Wed Jul 15 14:52:38 CST 2020
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pk_user
     *
     * @mbg.generated Wed Jul 15 14:52:38 CST 2020
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pk_user
     *
     * @mbg.generated Wed Jul 15 14:52:38 CST 2020
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pk_user
     *
     * @mbg.generated Wed Jul 15 14:52:38 CST 2020
     */
    User selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pk_user
     *
     * @mbg.generated Wed Jul 15 14:52:38 CST 2020
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pk_user
     *
     * @mbg.generated Wed Jul 15 14:52:38 CST 2020
     */
    int updateByPrimaryKey(User record);
}